In [1]:
import pandas as pd
import numpy as np

In [7]:
data = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]],
    [[9, 10], [11, 12]]
])

print("3d array:",data)

3d array: [[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


In [8]:
data.ndim

3

In [9]:
df=data+5
df

array([[[ 6,  7],
        [ 8,  9]],

       [[10, 11],
        [12, 13]],

       [[14, 15],
        [16, 17]]])